#!/bin/sh

set -eux

exec curl -v --tlsv1.3 --compressed \
     --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
     --header "Accept-Language: en-US,en;q=0.5" \
     --header "Upgrade-Insecure-Requests: 1" \
     --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0" \
     "$@"
